
package gcom.ws.atendimentopublico.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceRegistroAtendimento", targetNamespace = "http://impl.atendimentopublico.ws.gcom/", wsdlLocation = "http://localhost:8080/gsan/webservice/registroatendimento?wsdl")
public class WebServiceRegistroAtendimento
    extends Service
{

    private final static URL WEBSERVICEREGISTROATENDIMENTO_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEREGISTROATENDIMENTO_EXCEPTION;
    private final static QName WEBSERVICEREGISTROATENDIMENTO_QNAME = new QName("http://impl.atendimentopublico.ws.gcom/", "WebServiceRegistroAtendimento");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.43.116:8080/gsan/webservice/registroatendimento?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEREGISTROATENDIMENTO_WSDL_LOCATION = url;
        WEBSERVICEREGISTROATENDIMENTO_EXCEPTION = e;
    }

    public WebServiceRegistroAtendimento() {
        super(__getWsdlLocation(), WEBSERVICEREGISTROATENDIMENTO_QNAME);
    }

    public WebServiceRegistroAtendimento(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEREGISTROATENDIMENTO_QNAME, features);
    }

    public WebServiceRegistroAtendimento(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEREGISTROATENDIMENTO_QNAME);
    }

    public WebServiceRegistroAtendimento(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEREGISTROATENDIMENTO_QNAME, features);
    }

    public WebServiceRegistroAtendimento(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceRegistroAtendimento(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSRegistroAtendimentoImpl
     */
    @WebEndpoint(name = "WSRegistroAtendimentoImplPort")
    public WSRegistroAtendimentoImpl getWSRegistroAtendimentoImplPort() {
        return super.getPort(new QName("http://impl.atendimentopublico.ws.gcom/", "WSRegistroAtendimentoImplPort"), WSRegistroAtendimentoImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSRegistroAtendimentoImpl
     */
    @WebEndpoint(name = "WSRegistroAtendimentoImplPort")
    public WSRegistroAtendimentoImpl getWSRegistroAtendimentoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.atendimentopublico.ws.gcom/", "WSRegistroAtendimentoImplPort"), WSRegistroAtendimentoImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEREGISTROATENDIMENTO_EXCEPTION!= null) {
            throw WEBSERVICEREGISTROATENDIMENTO_EXCEPTION;
        }
        return WEBSERVICEREGISTROATENDIMENTO_WSDL_LOCATION;
    }

}
