
package gcom.ws.atendimentopublico.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSRegistroAtendimentoImpl", targetNamespace = "http://impl.atendimentopublico.ws.gcom/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSRegistroAtendimentoImpl {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "isOnline")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isOnline", targetNamespace = "http://impl.atendimentopublico.ws.gcom/", className = "gcom.ws.atendimentopublico.impl.IsOnline")
    @ResponseWrapper(localName = "isOnlineResponse", targetNamespace = "http://impl.atendimentopublico.ws.gcom/", className = "gcom.ws.atendimentopublico.impl.IsOnlineResponse")
    @Action(input = "isOnline", output = "http://impl.atendimentopublico.ws.gcom/WSRegistroAtendimentoImpl/isOnlineResponse")
    public String isOnline();

    /**
     * 
     * @param arg0
     * @return
     *     returns gcom.ws.atendimentopublico.impl.Resposta
     */
    @WebMethod(action = "pesquisarImovelOuUsuario")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pesquisarImovelOuUsuario", targetNamespace = "http://impl.atendimentopublico.ws.gcom/", className = "gcom.ws.atendimentopublico.impl.PesquisarImovelOuUsuario")
    @ResponseWrapper(localName = "pesquisarImovelOuUsuarioResponse", targetNamespace = "http://impl.atendimentopublico.ws.gcom/", className = "gcom.ws.atendimentopublico.impl.PesquisarImovelOuUsuarioResponse")
    @Action(input = "pesquisarImovelOuUsuario", output = "http://impl.atendimentopublico.ws.gcom/WSRegistroAtendimentoImpl/pesquisarImovelOuUsuarioResponse")
    public Resposta pesquisarImovelOuUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns gcom.ws.atendimentopublico.impl.Resposta
     */
    @WebMethod(action = "obter2ViaConta")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obter2ViaConta", targetNamespace = "http://impl.atendimentopublico.ws.gcom/", className = "gcom.ws.atendimentopublico.impl.Obter2ViaConta")
    @ResponseWrapper(localName = "obter2ViaContaResponse", targetNamespace = "http://impl.atendimentopublico.ws.gcom/", className = "gcom.ws.atendimentopublico.impl.Obter2ViaContaResponse")
    @Action(input = "obter2ViaConta", output = "http://impl.atendimentopublico.ws.gcom/WSRegistroAtendimentoImpl/obter2ViaContaResponse")
    public Resposta obter2ViaConta(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns gcom.ws.atendimentopublico.impl.Resposta
     */
    @WebMethod(action = "informarFaltaAgua")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "informarFaltaAgua", targetNamespace = "http://impl.atendimentopublico.ws.gcom/", className = "gcom.ws.atendimentopublico.impl.InformarFaltaAgua")
    @ResponseWrapper(localName = "informarFaltaAguaResponse", targetNamespace = "http://impl.atendimentopublico.ws.gcom/", className = "gcom.ws.atendimentopublico.impl.InformarFaltaAguaResponse")
    @Action(input = "informarFaltaAgua", output = "http://impl.atendimentopublico.ws.gcom/WSRegistroAtendimentoImpl/informarFaltaAguaResponse")
    public Resposta informarFaltaAgua(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns gcom.ws.atendimentopublico.impl.Resposta
     */
    @WebMethod(action = "solicitarRestabelecimento")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "solicitarRestabelecimento", targetNamespace = "http://impl.atendimentopublico.ws.gcom/", className = "gcom.ws.atendimentopublico.impl.SolicitarRestabelecimento")
    @ResponseWrapper(localName = "solicitarRestabelecimentoResponse", targetNamespace = "http://impl.atendimentopublico.ws.gcom/", className = "gcom.ws.atendimentopublico.impl.SolicitarRestabelecimentoResponse")
    @Action(input = "solicitarRestabelecimento", output = "http://impl.atendimentopublico.ws.gcom/WSRegistroAtendimentoImpl/solicitarRestabelecimentoResponse")
    public Resposta solicitarRestabelecimento(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
